# Generated by Django 6.0.6 on 2026-06-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
